[package]
name = "zain/bruhs-place-3"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "stravant/goodsignal@0.1.1"
FastCast = "encodedvenom/fastcastredux@0.1.3"
Roact = "roblox/roact@1.4.2"
Rodux = "roblox/rodux@3.0.0"
RoactRodux = "roblox/roact-rodux@0.3.0"
Hooks = "kampfkarren/roact-hooks@0.3.0"
Flipper = "reselim/flipper@2.0.0"
RoactFlipper = "reselim/roact-flipper@2.0.0"
# NOT INCLUDED: BehaviorTree3, RaycastHitboxV4, PartCache, ZonePlus

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
